name: Pip

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest]
        python-version: ["3.7", "3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools pytest "pybind11[global]"

    - name: Build and install
      run: |
        python setup.py bdist_wheel
        python -m pip install .

    - name: Test
      run: pytest tests/main.py

    - name: Fix ubuntu wheel
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        pip install auditwheel patchelf
        auditwheel repair --plat manylinux_2_35_x86_64 dist/*.whl
        rm -rf dist/*
        mv -v wheelhouse/* dist/

    - name: Publish to TestPyPi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
